version: "3.9"

services:
  api:
    container_name: openchat_api
    build: .
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www
    depends_on:
      - "db"

  db:
    container_name: openchat_db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
