version: "3.9"

services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./laravel:/var/www
    ports:
      - 80:80
    depends_on:
      - "fpm"

  fpm:
    container_name: openchat_api_fpm
    build: .
    volumes:
      - ./laravel:/var/www
    depends_on:
      - "db"

  db:
    container_name: openchat_db_nginx
    image: mysql:8.0.23
    command: mysqld --default-authentication-plugin=mysql_native_password --init-file /tmp/init.sql
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/tmp/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    cap_add:
      - SYS_NICE
